name: sonar-scanner
on:
#   pull_request:
#     branches: 
#       - develop  
  push:
      branches: 
        - develop  

jobs:
   
  SonarScanner:
   
    runs-on: ubuntu-latest
   
    steps:
    
    - name: checkout
      uses: actions/checkout@v1
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v1
    - name: Run sonarqube on push
      if: github.event_name == 'push' 
      env: 
      # to get access to secrets.SONAR_TOKEN, provide GITHUB_TOKEN
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PROJECT_KEY: VA
        HOST_URL: https://sonar.openbsl.ru
      run: sonar-scanner
       -Dsonar.login=${{ secrets.SONAR_TOKEN }}
       -Dsonar.host.url=$HOST_URL
       -Dsonar.projectKey=$PROJECT_KEY
#        -Dsonar.branch.name=${{ github.ref }}
    
#     - name: Run sonarqube on pull
#       if: github.event_name == 'pull_request' 
#       env: 
#       # to get access to secrets.SONAR_TOKEN, provide GITHUB_TOKEN
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       run: sonar-scanner
#        -X
#        -Dsonar.login=${{ secrets.SONAR_TOKEN }}
#        -Dsonar.host.url=https://sonar.openbsl.ru
#        -Dsonar.projectKey=VA
#        -Dsonar.pullrequest.key=${{ github.head_ref }}
#        -Dsonar.pullrequest.branch=${{ github.base_ref }}
#        -Dsonar.pullrequest.base=develop 
        
     
